name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run docs:build
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
  algolia:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # 将 checkout 动作更新至 v3
      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo ${{ secrets.ALGOLIA_CONFIG }} > algolia.json # 将敏感信息配置在 secrets 中，并使用环境变量输出到文件中
      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@v1 # 将动作更新至 v1
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          CONFIG: ${{ env.CONFIG }} # 使用环境变量代替 set-output 命令
        with:
          config_file_path: algolia.json # 指定配置文件路径
